/**
 * SOC workflow architecture diagram.
 */
export function SocWorkflowDiagram() {
  return (
    <svg viewBox="0 0 360 180" aria-label="SOC workflow architecture diagram">
      <defs>
        <marker
          id="soc-arrow"
          markerWidth="8"
          markerHeight="8"
          refX="6"
          refY="4"
          orient="auto"
          markerUnits="strokeWidth"
        >
          <path d="M 0 0 L 8 4 L 0 8 z" fill="var(--lime)" />
        </marker>
      </defs>

      <rect
        x="110"
        y="8"
        width="140"
        height="24"
        rx="7"
        fill="var(--bg-card)"
        stroke="var(--lime)"
      />
      <text
        x="180"
        y="23"
        textAnchor="middle"
        fill="var(--text-primary)"
        fontSize="10"
        fontWeight="700"
        fontFamily="var(--font-display)"
      >
        [React 19 + Jotai]
      </text>

      <rect
        x="62"
        y="44"
        width="104"
        height="24"
        rx="7"
        fill="var(--bg-card)"
        stroke="var(--custom-border)"
      />
      <text
        x="114"
        y="59"
        textAnchor="middle"
        fill="var(--text-muted)"
        fontSize="9"
        fontFamily="var(--font-display)"
      >
        [smsc-cases]
      </text>

      <rect
        x="194"
        y="44"
        width="104"
        height="24"
        rx="7"
        fill="var(--bg-card)"
        stroke="var(--custom-border)"
      />
      <text
        x="246"
        y="59"
        textAnchor="middle"
        fill="var(--text-muted)"
        fontSize="9"
        fontFamily="var(--font-display)"
      >
        [smsc-accounts]
      </text>

      <rect
        x="116"
        y="86"
        width="128"
        height="24"
        rx="7"
        fill="var(--bg-card)"
        stroke="var(--lime)"
      />
      <text
        x="180"
        y="100"
        textAnchor="middle"
        fill="var(--text-primary)"
        fontSize="10"
        fontWeight="700"
        fontFamily="var(--font-display)"
      >
        [AWS SQS + EventBridge]
      </text>
      <text
        x="180"
        y="118"
        textAnchor="middle"
        fill="var(--text-muted)"
        fontSize="9"
        fontFamily="var(--font-display)"
      >
        Event-driven sync
      </text>

      <rect
        x="28"
        y="144"
        width="122"
        height="24"
        rx="7"
        fill="var(--bg-card)"
        stroke="var(--custom-border)"
      />
      <text
        x="89"
        y="159"
        textAnchor="middle"
        fill="var(--text-muted)"
        fontSize="9"
        fontFamily="var(--font-display)"
      >
        [Genesys Cloud]
      </text>

      <rect
        x="188"
        y="144"
        width="144"
        height="24"
        rx="7"
        fill="var(--bg-card)"
        stroke="var(--custom-border)"
      />
      <text
        x="260"
        y="159"
        textAnchor="middle"
        fill="var(--text-muted)"
        fontSize="9"
        fontFamily="var(--font-display)"
      >
        [Ruby/Rails + PostgreSQL]
      </text>

      <line
        x1="170"
        y1="32"
        x2="126"
        y2="44"
        stroke="var(--lime)"
        strokeWidth="1.5"
        markerEnd="url(#soc-arrow)"
      />
      <line
        x1="190"
        y1="32"
        x2="234"
        y2="44"
        stroke="var(--lime)"
        strokeWidth="1.5"
        markerEnd="url(#soc-arrow)"
      />
      <line
        x1="114"
        y1="68"
        x2="89"
        y2="144"
        stroke="var(--lime)"
        strokeWidth="1.5"
        markerEnd="url(#soc-arrow)"
      />
      <text
        x="42"
        y="104"
        fill="var(--text-muted)"
        fontSize="9"
        fontFamily="var(--font-display)"
      >
        3-hop identity
      </text>
      <line
        x1="246"
        y1="68"
        x2="260"
        y2="144"
        stroke="var(--lime)"
        strokeWidth="1.5"
        markerEnd="url(#soc-arrow)"
      />
      <line
        x1="114"
        y1="68"
        x2="180"
        y2="86"
        stroke="var(--lime)"
        strokeWidth="1.5"
        markerEnd="url(#soc-arrow)"
      />
      <line
        x1="246"
        y1="68"
        x2="180"
        y2="86"
        stroke="var(--lime)"
        strokeWidth="1.5"
        markerEnd="url(#soc-arrow)"
      />
    </svg>
  );
}
